language: php
sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install
    - travis_retry nvm install v6.9.2
    - travis_retry npm install
    - travis_retry npm install -g gulp
    - travis_retry bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - composer test
    - gulp test

after_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then composer upload; fi
