language: php
sudo: false
dist: trusty

php:
    - 5.4
    - 5.6
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/
        - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=1

before_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '5.4' && $TRAVIS_PHP_VERSION != 'nightly' ]]; then phpenv config-rm xdebug.ini; fi
    - travis_retry composer self-update
    - travis_retry composer install
    - travis_retry nvm install 8
    - travis_retry npm install
    - travis_retry npm install -g gulp
    - travis_retry npm install -g greenkeeper-lockfile@1
    - greenkeeper-lockfile-update
    - travis_retry bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - chmod +x wp-cli.phar
    - mkdir $PWD/.bin
    - mv wp-cli.phar $PWD/.bin/wp
    - export PATH=$PATH:$PWD/.bin/
    - wp --version

script:
    - composer test
    - npm test
    # - npx dredd

after_script:
    - if [[ $TRAVIS_PHP_VERSION == '5.4' ]]; then composer upload; fi
    - greenkeeper-lockfile-upload

before_deploy:
    - gulp build:zip

deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: gAUbtuJKtw/mcBiZ1sAa6sCcCvfOThyc80bNRVf59gdUnV+8A+gwb6c0KV0tntcX/eJ6VmJHFtJGz18jGhMC6xklqkXxZB1xnyR4TpUgOMh6ZB30v/HH+rFj4rWxuXXejrQ5vqfM7jD1ZHOGqZYgGEX7f4LnlLMv9pCPmJBz4b4=
      file: wp-gistpen.zip
      on:
          repo: mAAdhaTTah/wp-gistpen
          tags: true
          php: 5.4
          all_branches: true
          condition: "$WP_MULTISITE == 0 && $WP_VERSION == 'latest'"
